### USER REGISTER
POST http://localhost:3003/api/register
Content-Type: application/json

{
  "name": "wasawasawasa",
  "email": "bit@connect.lt",
  "password": "labas123"
}

### USER LOGIN
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "email": "petras@grazulis.lt",
  "password": "labas123"
}